import Head from "next/head";
import Banner from "../components/banner/banner";
import SectionCards from "../components/card/section-cards";
import NavBar from "../components/nav/navbar";
import styles from "../styles/Home.module.css";

export interface DisneyVideosProps {
  imgUrl: string;
}

export default function Home() {
  const disneyVideos: DisneyVideosProps[] = [
    {
      imgUrl: "/static/clifford.webp"
    },
    {
      imgUrl: "/static/clifford.webp"
    },
    {
      imgUrl: "/static/clifford.webp"
    },
  ];

  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix</title>
        <link rel="icon" href="/favicon.ico" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <NavBar username="Ze Yen" />

      <Banner
        title="Clifford the red dog"
        subTitle="a very cute dog"
        imgUrl="/static/clifford.webp"
      />

      <div className={styles.sectionWrapper}>
        <SectionCards title="Disney" videos={disneyVideos} size="large" />
        <SectionCards title="Productivity" videos={disneyVideos} size="medium" />
      </div>

    </div>
  );
}
